#!/bin/bash

if [ ! -d /tmp/gcc ]; then
  pushd / >/dev/null
  curl --silent http://lambda.imoz.jp.s3-website-ap-northeast-1.amazonaws.com/lambda/gcc.tar.xz | xz -dc - | tar xvf - >/dev/null
  popd >/dev/null
fi

cp $HOME/input $HOME/input.cc
/tmp/gcc/bin/g++ -std=c++0x --static -o $HOME/output $HOME/input.cc
