#!/bin/bash
# imos-lambda
#
# Usage:
#     imos-lambda

source "$(dirname "${BASH_SOURCE}")"/imosh || exit 1
DEFINE_string input '' 'Input.'
DEFINE_string object '' 'Object.'
DEFINE_string region 'ap-northeast-1' 'Region.'
DEFINE_string function 'exec' 'Function name.'
DEFINE_string bucket '' 'Bucket name to read from/write to.'
DEFINE_string compiler '' 'Compiler.'
DEFINE_string compiler_flags '' 'Compiler flags.'
DEFINE_string arguments '' 'Extra arguments.'
DEFINE_int replicas 1 'The number of replicas.'
IMOSH_PREDICATE=1 eval "${IMOSH_INIT}"

IMOS_BIN="$(cd "$(dirname "${BASH_SOURCE}")"; pwd)"

lambda-invoke() {
  php "${IMOS_BIN}/library/imos-lambda.php" "$@"
}

if [ "${FLAGS_region}" != '' ]; then
  export IMOS_LAMBDA_REGION="${FLAGS_region}"
fi
if [ "${FLAGS_bucket}" != '' ]; then
  export IMOS_LAMBDA_BUCKET="${FLAGS_bucket}"
fi
if [ "${FLAGS_input}" != '' ]; then
  export IMOS_LAMBDA_INPUT="${FLAGS_input}"
fi
if [ "${FLAGS_object}" != '' ]; then
  export IMOS_LAMBDA_OBJECT="${FLAGS_object}"
fi

if [ "${FLAGS_compiler}" != '' ]; then
  if [ "${IMOS_LAMBDA_INPUT}" == '' ]; then
    LOG FATAL '--input must be specified to compile.'
  fi
  LOG INFO 'Compiling...'
  if ! IMOS_LAMBDA_FUNCTION="${FLAGS_compiler}" \
       IMOS_LAMBDA_ARGUMENTS="${FLAGS_compiler_flags}" \
       IMOS_LAMBDA_PRINT='output' \
          lambda-invoke >"${TMPDIR}/output"; then
    LOG FATAL 'Failed to compile.'
  fi
  export IMOS_LAMBDA_OBJECT="$(cat "${TMPDIR}/output")"
  LOG INFO "Successfully compiled: ${IMOS_LAMBDA_OBJECT}"
  unset IMOS_LAMBDA_INPUT
fi

export IMOS_LAMBDA_FUNCTION="${FLAGS_function}"
if [ "${FLAGS_arguments}" != '' ]; then
  export IMOS_LAMBDA_ARGUMENTS="${FLAGS_arguments}"
fi
export IMOS_LAMBDA_REPLICAS="${FLAGS_replicas}"
LOG INFO 'Invoking function.'
lambda-invoke "$@"
LOG INFO 'Completed.'
